site_name: Refiners
site_description: A micro framework on top of PyTorch with first class citizen APIs for foundation model adaptation
repo_name: Refiners
repo_url: https://github.com/finegrain-ai/refiners
edit_uri: edit/main/docs/
copyright: Â© Lagon Technologies
theme:
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  name: material
  custom_dir: docs/overrides
  palette:
    primary: deep orange
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - navigation.tabs.sticky
    - content.code.copy
    - announce.dismiss
plugins:
  - search
  - tags
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings:
      handlers:
        python:
          import:
            - https://docs.python.org/3/objects.inv
            - https://pytorch.org/docs/master/objects.inv
            - https://docs.kidger.site/jaxtyping/objects.inv
          options:
            show_bases: true
            show_source: true
            show_root_toc_entry: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_if_no_docstring: false
            filters:
              - "!^_"
            docstring_options:
              ignore_init_summary: true
            merge_init_into_class: true
            separate_signature: true
            show_signature_annotations: true
            signature_crossrefs: true
watch:
  - src/refiners
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 
    - Welcome: index.md
    - Manifesto: home/why.md
  - Getting started:
    - getting-started/recommended.md
    - getting-started/advanced.md
  - Key Concepts:
    - concepts/chain.md
    - concepts/context.md
    - concepts/adapter/index.md
  - Guides:
    - Adapting SDXL: guides/adapting_sdxl/index.md
  - API Reference:
      - Refiners: reference/
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mCmjNUVV7d
    - icon: fontawesome/brands/github
      link: https://github.com/finegrain-ai/refiners   
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/finegrain_ai 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/finegrain-ai/
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
validation:
  links:
    absolute_links: info  # use relative_to_docs when we switch to mkdocs 1.6
