site_name: Refiners
site_description: A micro framework on top of PyTorch with first class citizen APIs for foundation model adaptation
repo_name: Refiners
repo_url: https://github.com/finegrain-ai/refiners
edit_uri: edit/main/docs/
copyright: Â© Lagon Technologies
theme:
  favicon: assets/favicon.svg
  logo: assets/favicon.svg
  name: material
  palette:
    primary: deep orange
    accent: deep orange
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.tabs.sticky
    - content.code.copy
plugins:
  - mkdocstrings
  - search
  - tags
extra_css:
  - stylesheets/extra.css
nav:
  - Home: 
    - index.md
  - Getting started: getting_started.md
  - Models: 
    - models/index.md
    - models/latent_diffusion.md
    - models/segment_anything.md
  - Fluxion:
    - fluxion/index.md
    - fluxion/adapters.md
  - Training utils: 
    - training_utils/index.md
  - Contributing:
    - contributing/index.md
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/mCmjNUVV7d
    - icon: fontawesome/brands/github
      link: https://github.com/finegrain-ai/refiners   
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/finegrain_ai 
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/finegrain-ai/
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true